# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# Indicates that it’s a free app.
price_tier(0)

# Answer the questions Apple would present to you upon manually submitting for review
submission_information({
   export_compliance_encryption_updated: false,
   export_compliance_uses_encryption: false,
   content_rights_contains_third_party_content: false,
   add_id_info_uses_idfa: false
})

# file location
ipa("./fastlane/builds/hello-fastlane.ipa")

# option to automatically submit the app for review (turned off here)
submit_for_review(false)

automatic_release(false)